In [30]:
import pandas as pd
import numpy as np
dataset_path="./ranking_dataset.csv"
df=pd.read_csv(dataset_path)
df.head()

,val_0,val_1,val_2,val_3,val_4,val_5,val_6,val_7,val_8,val_9,rank_0,rank_1,rank_2,rank_3,rank_4,rank_5,rank_6,rank_7,rank_8,rank_9
0,542,67,876,414,26,335,620,924,950,113,5,1,7,4,0,3,6,8,9,2
1,378,14,210,954,231,572,315,295,567,706,5,0,1,9,2,7,4,3,6,8
2,749,876,73,111,899,213,541,769,287,219,6,8,0,1,9,2,5,7,4,3
3,372,880,475,329,733,564,739,376,632,10,2,9,4,1,7,5,8,3,6,0
4,186,822,577,519,707,123,143,294,693,677,2,9,5,4,8,0,1,3,7,6

In [24]:

input_df=df[[f"val_{x}" for x in range(10)]]
output_df=df[[f"rank_{x}" for x in range(10)]]

input_df

      val_0  val_1  val_2  val_3  val_4  val_5  val_6  val_7  val_8  val_9
0       542     67    876    414     26    335    620    924    950    113
1       378     14    210    954    231    572    315    295    567    706
2       749    876     73    111    899    213    541    769    287    219
3       372    880    475    329    733    564    739    376    632     10
4       186    822    577    519    707    123    143    294    693    677
...     ...    ...    ...    ...    ...    ...    ...    ...    ...    ...
9995    930    260    396    754    449    382    145    246    537    518
9996    315    847    156    752    280    956    218    727    620    217
9997    449    552    620    136    610     69    717    589    851    886
9998    491    746    689    385     87    209    856    974    397    312
9999    787    529      1    102    405    806    823    194    115    365

[10000 rows x 10 columns]

In [25]:
#First, we find the maximum and minimum of the input as well as the number of unique values

print("Global maximum:",input_df.max().max())
print("Global minimum:", input_df.min().min())
print("Maximum Range in a sequence:\n",(input_df.max(axis=1)-input_df.min(axis=1)).abs().max())
print("num_unique:" ,input_df.stack().nunique())

Global maximum: 999
Global minimum: 0
Maximum Range in a sequence:
 999
num_unique: 1000

In [ ]:
rows_with_dupes = input_df[input_df.nunique(axis=1) < len(input_df.columns)]
ranks_with_dupes= output_df[output_df.nunique(axis=1) < len(output_df.columns)]
ranks_of_dupes = output_df[input_df.nunique(axis=1) < len(input_df.columns)]
print(len(ranks_with_dupes))
print(len(rows_with_dupes))

0
429

In [27]:
rows_with_dupes

      val_0  val_1  val_2  val_3  val_4  val_5  val_6  val_7  val_8  val_9
36      827    208     80    761    854    342    837    241    850    854
82      606    507     69    606    623    699    978     81    174    823
95      306    963    828    483     18     18    707    920    145    838
96      568     16    869    870      6    168    428    325    869    274
110     242    169    659     16    813    659    244    429    557    738
...     ...    ...    ...    ...    ...    ...    ...    ...    ...    ...
9829     55    383    545     32    510    333    306    383     79    830
9898    448    576    477    748    748    988     37    710    194    248
9901    218     79    922    475    154    293    218    909    692    658
9921     88    217    628    861    230    111    351    628    915      4
9981    510     21     27    391    931    961    300     44    575    391

[429 rows x 10 columns]

In [38]:
stable_ranks=(input_df.rank(axis=1, method='first').astype(int) - 1)

(stable_ranks.to_numpy()==output_df.to_numpy()).all()

np.True_